-- SESION 16
-- EJERCICIO PRÁCTICO - SESIÓN 16 (AUDITORÍA Y TRANSACCIONES)

CREATE TABLE auditoria_pedidos (
    audit_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
    pedido_id NUMBER,
    accion VARCHAR2(30),
    fecha TIMESTAMP,
    comentario VARCHAR2(200)
);
/

CREATE OR REPLACE TRIGGER trg_auditoria_pedidos
AFTER INSERT OR UPDATE OR DELETE ON Pedidos
FOR EACH ROW
DECLARE
    PRAGMA AUTONOMOUS_TRANSACTION;
BEGIN
    IF INSERTING THEN
        INSERT INTO auditoria_pedidos(pedido_id, accion, fecha, comentario)
        VALUES(:NEW.PedidoID, 'INSERT', SYSTIMESTAMP, 'Pedido creado');
    ELSIF UPDATING THEN
        INSERT INTO auditoria_pedidos(pedido_id, accion, fecha, comentario)
        VALUES(:NEW.PedidoID, 'UPDATE', SYSTIMESTAMP, 'Pedido actualizado: total ' || :NEW.Total);
    ELSIF DELETING THEN
        INSERT INTO auditoria_pedidos(pedido_id, accion, fecha, comentario)
        VALUES(:OLD.PedidoID, 'DELETE', SYSTIMESTAMP, 'Pedido eliminado');
    END IF;
    COMMIT;
END;
/

CREATE OR REPLACE PROCEDURE procesar_pedido_con_inventario(p_pedido_id IN NUMBER) AS
    CURSOR c_detalles IS
        SELECT ProductoID, Cantidad
        FROM DetallesPedidos
        WHERE PedidoID = p_pedido_id;
    v_stock NUMBER;
BEGIN
    FOR r IN c_detalles LOOP
        SELECT Cantidad INTO v_stock
        FROM Inventario
        WHERE ProductoID = r.ProductoID
        FOR UPDATE;

        IF v_stock < r.Cantidad THEN
            RAISE_APPLICATION_ERROR(-20010, 'Stock insuficiente para producto ' || r.ProductoID);
        END IF;

        UPDATE Inventario
        SET Cantidad = Cantidad - r.Cantidad
        WHERE ProductoID = r.ProductoID;
    END LOOP;

    COMMIT;
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ERROR en procesar pedido: ' || SQLERRM);
        ROLLBACK;
END procesar_pedido_con_inventario;
/

BEGIN
    DBMS_OUTPUT.PUT_LINE('=== PRUEBA SESIÓN 16: Auditoría y transacciones ===');
    procesar_pedido_con_inventario(101);
    DBMS_OUTPUT.PUT_LINE('Inventario actualizado.');
END;
/

SELECT * FROM auditoria_pedidos;
